name: gerenciador_aula
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^0.5.7+3
  google_fonts: ^1.1.0
  flushbar: ^1.10.4
  font_awesome_flutter: ^8.8.1
  cupertino_icons: ^0.1.3
  intl: ^0.16.1
  get: ^2.14.1
  flutter_launcher_icons: ^0.7.5

dev_dependencies:
  # flutter_test:
  #   sdk: flutter
  
flutter_icons:
  android: true
  ios: true
  image_path: "assets/book.png"
  

flutter:

  uses-material-design: true

  assets:
    - assets/book.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
